# msg

uint8 id
uint16 life_cycle

float32 dist_x
float32 dist_y
float32 dist_height
float32 dist_x_stdv
float32 dist_y_stdv

float32 v_abs_x
float32 v_abs_y
float32 v_abs_x_stdv
float32 v_abs_y_stdv

float32 a_abs_x
float32 a_abs_y
float32 a_abs_x_stdv
float32 a_abs_y_stdv

float32 length
float32 width

float32 orient
float32 yaw_rate
float32 orient_stdv
float32 yaw_rate_stdv

float32 rcs
uint8 micro_doppler_flag

uint8 classification
uint8 class_conf
uint8 prob_of_exist
uint8 dyn_prop
uint8 dyn_prop_conf
uint8 mirror_prob
uint8 obstacle_prob
uint8 maint_state
uint8 ref_pt

uint8 msg_cnt
uint32 crc16_checksum